services:
  finplanbot:
    build:
      context: ../services/finplanbot
    image: finplanbot:latest           
    container_name: finplan-bot
    env_file:
      - ../.env
    volumes:
      - ../services/finplanbot:/app
    restart: unless-stopped

