
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - /etc/mybot.env
    environment:
      RABBITMQ_DEFAULT_VHOST: finplanbot
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_LOAD_DEFINITIONS: "false"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  finplanbot:
    build:
      context: ../services/finplanbot
    image: finplanbot:latest
    container_name: finplan-bot
    env_file:
      - /etc/mybot.env
    volumes:
      - ../services/finplanbot:/app
    depends_on:
      - rabbitmq
    restart: unless-stopped
  message-processor:
    build:
      context: ../services/message-processor
    image: message-processor:latest
    container_name: message-processor
    env_file:
      - /etc/mybot.env   
    extra_hosts:
      - "host.docker.internal:host-gateway"       
    depends_on:
      - rabbitmq
    restart: unless-stopped
volumes:
  rabbitmq_data:
