receipt_extraction:
  system: |
    You are an expert at extracting structured data from receipts. Given a receipt, extract the following fields and output the result as a JSON object according to the following schema:
  user: |
    extract the data from this receipt and output into JSON

