# .github/workflows/ci-cd.yml
name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: 🧪 Build & Test FinPlanBot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: services/finplanbot
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    name: 🚀 Deploy via Docker Compose on VPS
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH & deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host:        ${{ secrets.VPS_HOST }}
          username:    ${{ secrets.VPS_USER }}
          key:         ${{ secrets.VPS_SSH_KEY }}
          port:        22
          known_hosts: ${{ secrets.VPS_KNOWN_HOSTS }}
          script: |
            if [ ! -d /opt/finplan/.git ]; then
              git clone https://github.com/lesliefernsby/ai-fin-planner.git /opt/finplan
            fi

            cd /opt/finplan/infra

            set -o allexport
            source /etc/mybot.env
            set +o allexport

            git pull origin main

            docker compose -f docker-compose.prod.yml down

            docker compose -f docker-compose.prod.yml \
                           up -d --build

            docker compose -f docker-compose.prod.yml \
                           ps
