name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1️⃣ Build & Test
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install deps & run tests
        working-directory: services/finplanbot
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # 2️⃣ Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Build & Push Image
      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: services/finplanbot
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/finplanbot:latest

  deploy:
    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host:        ${{ secrets.VPS_HOST }}
        username:    ${{ secrets.VPS_USER }}
        key:         ${{ secrets.VPS_SSH_KEY }}
        known_hosts: ${{ secrets.VPS_KNOWN_HOSTS }}
        script: |
          cd /opt/finplan/infra

          # load secrets for interpolation
          set -o allexport
          source /etc/mybot.env
          set +o allexport

          git pull origin main

          docker-compose -f docker-compose.yml -f docker-compose.prod.yml down
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

          docker-compose -f docker-compose.yml -f docker-compose.prod.yml ps